<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rustic Granite Shoes  Totam quibusdam v_5fbddf</name>
   <tag></tag>
   <elementGuidId>d9896ac0-d56e-4051-be5d-e56a79d752ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#12889</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='12889']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a56ef8b2-3dfb-4324-98bc-7f4a18398b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>12889</value>
      <webElementGuid>82afc329-0d49-4c75-8163-4722fe8a6bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-4 col-lg-3 col-6</value>
      <webElementGuid>f989b47e-3b50-4ab4-ade9-f92972bd451c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Rustic Granite Shoes  Totam quibusdam vel.   3  Rp 46DetailBeli</value>
      <webElementGuid>a4ebb4a6-54fc-4658-a8a0-ab536f6445b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;12889&quot;)</value>
      <webElementGuid>abfded87-4e58-433f-886c-a9d47b602632</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='12889']</value>
      <webElementGuid>b3034dc3-2765-4a2e-932f-559043289e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[2]/div/div[3]</value>
      <webElementGuid>a910310c-5c50-49c8-9def-b436c531ee28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beli'])[2]/following::div[1]</value>
      <webElementGuid>dabba002-b1e9-4a21-8ac1-6ccad1157510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[2]/following::div[1]</value>
      <webElementGuid>7b4bd55d-5eb0-4ea1-85d5-d345b25bf2c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]</value>
      <webElementGuid>c959f568-430c-4718-81b3-84089bdfccfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '12889' and (text() = ' Rustic Granite Shoes  Totam quibusdam vel.   3  Rp 46DetailBeli' or . = ' Rustic Granite Shoes  Totam quibusdam vel.   3  Rp 46DetailBeli')]</value>
      <webElementGuid>1aa92e56-7c88-4d9e-b196-f5c8491b083c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
