<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_AltaShop_v-icon notranslate fas fa-shoppi_c66ce9</name>
   <tag></tag>
   <elementGuidId>d16c5ae0-bb8c-4b99-95b2-911c8209fba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.v-icon.notranslate.fas.fa-shopping-cart.theme--dark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/header/div/button/span/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5191fa02-88b5-4b99-b152-ea33637e53a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dd15787b-c67e-4f03-8858-d6a8a0fa2e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-icon notranslate fas fa-shopping-cart theme--dark</value>
      <webElementGuid>c9b1892f-f9ef-4bf4-a202-9934beba90b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/header[@class=&quot;v-sheet theme--dark v-toolbar v-app-bar v-app-bar--fixed deep-purple accent-4&quot;]/div[@class=&quot;v-toolbar__content&quot;]/button[@class=&quot;v-btn v-btn--icon v-btn--round theme--dark v-size--default&quot;]/span[@class=&quot;v-btn__content&quot;]/span[@class=&quot;v-badge v-badge--bottom v-badge--left v-badge--overlap theme--dark&quot;]/i[@class=&quot;v-icon notranslate fas fa-shopping-cart theme--dark&quot;]</value>
      <webElementGuid>6a781293-2288-42eb-a46c-e8e8035b401a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/header/div/button/span/span/i</value>
      <webElementGuid>802d987c-e8f9-496c-abb0-40c958377ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>5da491cd-f748-4a89-910b-611ec559b03c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
