<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Practical Marble Table  Temporibus sunt_7767f8</name>
   <tag></tag>
   <elementGuidId>a5411ccd-4187-4156-9a11-02ffae02ef9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#12888</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='12888']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6f0e088a-ddae-46b4-809e-d34740f8e18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>12888</value>
      <webElementGuid>5224d1b8-1a09-4713-b85d-4d26fb380c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-4 col-lg-3 col-6</value>
      <webElementGuid>1ad8df27-d9b6-4f6f-a41b-5af68d603a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Practical Marble Table  Temporibus sunt asperiores.   5  Rp 82DetailBeli</value>
      <webElementGuid>2e02b9fc-3af9-4beb-b1a8-2052dec8942f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;12888&quot;)</value>
      <webElementGuid>f63fb9a9-bc9e-4f47-a7f7-b373693a7ba5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='12888']</value>
      <webElementGuid>5310675d-a484-405f-9d1b-ba9ece7b04ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[2]/div/div[2]</value>
      <webElementGuid>3ea0f169-1d6a-4227-a9cb-411db4a952f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beli'])[1]/following::div[1]</value>
      <webElementGuid>2921a437-37a7-448a-a721-23af866596de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[1]/following::div[1]</value>
      <webElementGuid>e795b8ec-0220-4a33-bcda-1dbcbbfe2b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>2275899b-842b-44ea-b176-9fc58d6c6e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '12888' and (text() = ' Practical Marble Table  Temporibus sunt asperiores.   5  Rp 82DetailBeli' or . = ' Practical Marble Table  Temporibus sunt asperiores.   5  Rp 82DetailBeli')]</value>
      <webElementGuid>adce745d-f03c-45cf-ac21-bd439d4e1abd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
